import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, TextInput, FlatList, KeyboardAvoidingView, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute } from '@react-navigation/native';
import { colors } from '../theme/colors';
import { supabase } from '../lib/supabase';
import io from 'socket.io-client';
import { LIVE_CONFIG } from '../config/api';

// We use modern Expo Video for playing the HLS Stream generated by the VPS 
// npx expo install expo-video
let useVideoPlayer: any, VideoView: any;
try {
  const expoVideo = require('expo-video');
  useVideoPlayer = expoVideo.useVideoPlayer;
  VideoView = expoVideo.VideoView;
} catch (e) {}

const BACKEND_URL = LIVE_CONFIG.CHAT_SERVER;
const HLS_SERVER = LIVE_CONFIG.HLS_VIEW;

export const LiveViewerScreen = () => {
  const navigation = useNavigation() as any;
  const route = useRoute() as any;
  // Assume we passed { roomId: 'auction_123', hostName: 'أحمد' } via navigation
  const { roomId = 'auction_test', hostName = 'البائع' } = route.params || {};

  const [viewerCount, setViewerCount] = useState(0);
  const [liveChatMessages, setLiveChatMessages] = useState<any[]>([]);
  const [myMessage, setMyMessage] = useState('');
  
  const socketRef = useRef<any>(null);
  const flatListRef = useRef<FlatList>(null);
  const [profile, setProfile] = useState<any>(null);

  // Initialize Video Player for HLS Stream playback
  const player = useVideoPlayer?.(`${HLS_SERVER}/${roomId}/index.m3u8`, (playerInstance: any) => {
    playerInstance.loop = true;
    playerInstance.play();
  });

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      if (user) {
        supabase.from('profiles').select('*').eq('id', user.id).single()
          .then(({ data }) => setProfile(data));
      }
    });

    socketRef.current = io(BACKEND_URL);
    socketRef.current.emit('join_room', roomId);

    socketRef.current.on('viewers_update', (count: number) => {
      setViewerCount(count);
    });

    socketRef.current.on('chat_message', (msg: any) => {
      setLiveChatMessages(prev => [...prev, msg]);
      setTimeout(() => flatListRef.current?.scrollToEnd({ animated: true }), 100);
    });

    return () => {
      socketRef.current.emit('leave_room', roomId);
      socketRef.current.disconnect();
    };
  }, [roomId]);

  const sendMessage = () => {
    if (!myMessage.trim() || !socketRef.current) return;
    socketRef.current.emit('send_message', {
      roomId,
      user: profile?.full_name || 'عضو (مجهول)',
      text: myMessage.trim()
    });
    setMyMessage('');
  };

  return (
    <View style={styles.container}>
      {/* BACKGROUND VIDEO PLAYER */}
      {VideoView ? (
        <VideoView style={styles.videoPlayer} player={player} allowsFullscreen={false} contentFit="cover" />
      ) : (
         <View style={styles.nativeWarning}>
             <Text style={{color: 'white', textAlign: 'center'}}>يرجى تثبيت expo-video لتشغيل البث</Text>
         </View>
      )}

      {/* FOREGROUND TIKTOK OVERLAY */}
      <SafeAreaView style={styles.overlay} pointerEvents="box-none">
        
        {/* TOP HUD */}
        <View style={styles.topHud}>
          <TouchableOpacity style={styles.avatarHost} onPress={() => navigation.goBack()}>
             <Ionicons name="arrow-back" size={24} color="#FFF" />
          </TouchableOpacity>
          <View style={{marginLeft: 10}}>
             <Text style={styles.hostName}>{hostName}</Text>
             <View style={styles.liveBadge}><Text style={styles.liveText}>البائع يبث الآن</Text></View>
          </View>
          
          <View style={styles.statsBadge}>
            <Ionicons name="eye" size={16} color="#FFF" style={{marginRight: 4}}/>
            <Text style={styles.hudText}>{viewerCount}</Text>
          </View>
        </View>

        <View style={styles.flexSpacer} pointerEvents="none" />

        {/* CHAT BOX */}
        <View style={styles.chatContainer}>
          <FlatList
            ref={flatListRef}
            data={liveChatMessages}
            keyExtractor={(_, index) => index.toString()}
            showsVerticalScrollIndicator={false}
            renderItem={({ item }) => (
              <View style={styles.chatMessage}>
                <Text style={styles.chatUser}>{item.user}</Text>
                <Text style={styles.chatText}>{item.text}</Text>
              </View>
            )}
            ListEmptyComponent={<Text style={styles.welcomeText}>أنت أول من دخل إلى البث المباشر!</Text>}
          />
        </View>

        {/* BOTTOM INPUT */}
        <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
            <View style={styles.bottomInteractions}>
                <TextInput 
                    placeholder="اكتب مزايدتك هنا..."
                    placeholderTextColor="#DDD"
                    style={styles.chatInputNode}
                    value={myMessage}
                    onChangeText={setMyMessage}
                    onSubmitEditing={sendMessage}
                />
                <TouchableOpacity style={styles.actionIconRound} onPress={sendMessage}>
                  <Ionicons name="send" size={20} color="#000" />
                </TouchableOpacity>
            </View>
        </KeyboardAvoidingView>

      </SafeAreaView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  videoPlayer: { ...StyleSheet.absoluteFillObject },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.1)' },
  nativeWarning: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  topHud: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, marginTop: 15 },
  avatarHost: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  hostName: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
  liveBadge: { backgroundColor: '#FF3B30', paddingHorizontal: 6, borderRadius: 4, alignSelf: 'flex-start', marginTop: 2 },
  liveText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  statsBadge: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  hudText: { color: '#FFF', fontWeight: '600' },
  flexSpacer: { flex: 1 },
  chatContainer: { height: 250, paddingHorizontal: 15, marginBottom: 10 },
  chatMessage: { backgroundColor: 'rgba(0,0,0,0.4)', alignSelf: 'flex-start', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 18, marginBottom: 10, maxWidth: '85%' },
  chatUser: { color: colors.primary, fontWeight: 'bold', fontSize: 14, marginBottom: 4 },
  chatText: { color: '#FFF', fontSize: 15, lineHeight: 20 },
  welcomeText: { color: '#FFF', textAlign: 'center', marginTop: 50, opacity: 0.6 },
  bottomInteractions: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, paddingBottom: 25 },
  chatInputNode: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', height: 50, borderRadius: 25, paddingHorizontal: 20, color: '#FFF', marginRight: 10 },
  actionIconRound: { backgroundColor: colors.primary, width: 45, height: 45, borderRadius: 22.5, justifyContent: 'center', alignItems: 'center' }
});
